import type {
  Comparable,
  MarketContext,
  PropertyDetails,
} from '@/lib/types';

export const MOCK_SUBJECT: PropertyDetails = {
  addressKey: 'mock-baulkham-hills-42-example-st',
  fullAddress: '42 Example Street, Baulkham Hills NSW 2153',
  suburb: 'Baulkham Hills',
  state: 'NSW',
  postcode: '2153',
  locPid: 'NSW231',
  landAreaSqm: 620,
  bedrooms: 4,
  bathrooms: 2,
  carSpaces: 2,
  yearBuilt: 1995,
  propertyType: 'House',
};

export const MOCK_MARKET: MarketContext = {
  locPid: 'NSW231',
  suburb: 'Baulkham Hills',
  state: 'NSW',
  annualisedGrowth5y: 0.072,
  cycleStage: 'Rising',
  typicalDaysOnMarket: 38,
  typicalPrice: 528_000,
  medianSalePrice: 520_000,
};

/**
 * Sale dates are set a fixed number of days in the past so the indexed
 * values stay stable regardless of when the mock is evaluated.
 */
function daysAgoIso(days: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString();
}

export const MOCK_COMPARABLES: Comparable[] = [
  {
    addressKey: 'mock-comp-1',
    fullAddress: '8 Sample Crescent, Baulkham Hills NSW 2153',
    salePrice: 505_000,
    saleDateIso: daysAgoIso(28),
    landAreaSqm: 610,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.4,
    htagAdjustmentFactor: 1.02,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-2',
    fullAddress: '15 Demo Avenue, Baulkham Hills NSW 2153',
    salePrice: 518_000,
    saleDateIso: daysAgoIso(52),
    landAreaSqm: 640,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.8,
    htagAdjustmentFactor: 0.99,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-3',
    fullAddress: '27 Placeholder Road, Baulkham Hills NSW 2153',
    salePrice: 495_000,
    saleDateIso: daysAgoIso(75),
    landAreaSqm: 580,
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 1.1,
    htagAdjustmentFactor: 1.04,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-4',
    fullAddress: '33 Fixture Close, Baulkham Hills NSW 2153',
    salePrice: 540_000,
    saleDateIso: daysAgoIso(94),
    landAreaSqm: 650,
    bedrooms: 4,
    bathrooms: 3,
    carSpaces: 2,
    distanceKm: 0.9,
    htagAdjustmentFactor: 0.97,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-5',
    fullAddress: '49 Seed Street, Baulkham Hills NSW 2153',
    salePrice: 522_000,
    saleDateIso: daysAgoIso(40),
    landAreaSqm: 630,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.6,
    htagAdjustmentFactor: 1.0,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-6',
    fullAddress: '12 Dummy Drive, Baulkham Hills NSW 2153',
    salePrice: 488_000,
    saleDateIso: daysAgoIso(110),
    landAreaSqm: 570,
    bedrooms: 3,
    bathrooms: 1,
    carSpaces: 1,
    distanceKm: 1.4,
    htagAdjustmentFactor: 1.08,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-7',
    fullAddress: '71 Test Grove, Baulkham Hills NSW 2153',
    salePrice: 558_000,
    saleDateIso: daysAgoIso(61),
    landAreaSqm: 700,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 1.0,
    htagAdjustmentFactor: 0.94,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-8',
    fullAddress: '4 Prototype Place, Baulkham Hills NSW 2153',
    salePrice: 530_000,
    saleDateIso: daysAgoIso(35),
    landAreaSqm: 620,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.5,
    htagAdjustmentFactor: 0.98,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-9',
    fullAddress: '19 Specimen Street, Baulkham Hills NSW 2153',
    salePrice: 512_000,
    saleDateIso: daysAgoIso(82),
    landAreaSqm: 600,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.7,
    htagAdjustmentFactor: 1.01,
    propertyType: 'House',
  },
  {
    addressKey: 'mock-comp-10',
    fullAddress: '63 Example Street, Baulkham Hills NSW 2153',
    salePrice: 548_000,
    saleDateIso: daysAgoIso(22),
    landAreaSqm: 660,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    distanceKm: 0.3,
    htagAdjustmentFactor: 0.96,
    propertyType: 'House',
  },
];

export const MOCK_LISTING_DESCRIPTION = `Beautifully presented four-bedroom family home in a sought-after pocket of Baulkham Hills. The vendor says sell — relocation means this one needs to go. Open plan living, updated kitchen, low-maintenance gardens, double garage. Walking distance to shops and schools.`;
